# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_flood_ident_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood',
            name='ident_msg',
            field=models.BooleanField(default=None),
        ),
    ]
